# Generated by Django 4.2.7 on 2025-11-23 06:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('ORDER_DUE', 'Order Due'), ('ORDER_OVERDUE', 'Order Overdue'), ('STOCK_PARITY', 'Stock Parity Issue'), ('SUPPLIER_RATING', 'Supplier Rating Update'), ('PR_ALERT', 'Purchase Request Alert'), ('PO_ALERT', 'Purchase Order Alert'), ('INVOICE_ALERT', 'Invoice Alert')], max_length=20),
        ),
        migrations.CreateModel(
            name='SupplierEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('notes', models.TextField(blank=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='erp_app.supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplier Evaluations',
                'ordering': ['-created_at'],
            },
        ),
    ]
